### ISSUE TITLE
Android font rendering problem

### ISSUE THREAD

**Issue by mypark** [shoutem/ui#257] opened 2017-05-20 14:54 UTC
On Android, the font renders badly with weird thin/thick weights.

could be a duplicate of closed issue: font rendering issues in android #118  https://github.com/shoutem/ui/issues/118

![font_problem](https://cloud.githubusercontent.com/assets/470164/26276744/17a19c70-3d4b-11e7-8941-b384db517c40.png)

**Comment by Talor-A** [comment] 2017-06-02 23:18
happens to me as well.

**Comment by tafelito** [comment] 2017-06-07 06:18
+1

**Comment by Talor-A** [comment] 2017-08-05 17:57
is there a way to remove the custom font from all shoutem components to avoid this problem?

**Comment by Vladimir-Vdovic** [comment] 2017-08-06 10:55
@Talor-A You can modify the `theme.js` file [in the UI toolkit](https://github.com/shoutem/ui/blob/develop/theme.js) to determine the font used by different components.

**Comment by mypark** [comment] 2017-09-05 01:10
So is the suggested solution to change the font away from Rubik in Android?

**Comment by Vladimir-Vdovic** [comment] 2017-09-07 14:54
It seems the issue is only with Rubik-Regular.

[Here](https://stackoverflow.com/questions/46054523/shoutem-change-default-fontfamily-not-work/46058338#46058338) you can see how to override the default theme variables, including the fontFamily of certain components. This would be a workaround for the time being.

We'll look into the issue more closely to see if we can resolve Rubik-Regular's rendering on Android.

**Comment by Unforgiven-wanda** [comment] 2017-11-21 11:01
Replacing the fonts inside the folder `myproject/android/app/src/main/assets/fonts/` with the ones downloaded from [Google fonts](https://fonts.google.com/specimen/Rubik?selection.family=Rubik:300,300i,400,400i,500,500i,700,700i,900,900i) fixed it for me
The downside is that I have to perform this action whenever I install a new package or use `react-native link`

See
![1](https://user-images.githubusercontent.com/4499783/33069108-b7ec4b68-ceb3-11e7-8fbf-1839d39771be.png)
![2](https://user-images.githubusercontent.com/4499783/33069113-ba7ab5e0-ceb3-11e7-8141-389e09b4b8ec.png)
![3](https://user-images.githubusercontent.com/4499783/33069121-bc6254a8-ceb3-11e7-8d7a-6c95127fbabc.png)

**Comment by Vladimir-Vdovic** [comment] 2017-12-18 17:43
Hey guys.

This issue has been resolved with version 0.22.1 of the UI toolkit. Android and iOS should now render the font identically.

**Closed by Vladimir-Vdovic** 2017-12-18 17:43 UTC
Labels: bug
