### ISSUE TITLE
Play video from native url ( file:// )  with WebView ?

### ISSUE THREAD

**Issue by tdurand** [shoutem/ui#46] opened 2016-09-28 02:13 UTC
Hi there, 

I'm currently working on integrating Video to my app, and i saw that you are working on releasing a Video components (that's great). Looking at the code i saw that you settled on using WebView to play all kind of videos: https://github.com/shoutem/ui/pull/27 .

**My question is, have you been able to play a video from a local video (on ios device) ?** 

Because for me it doesn't work for uri starting with file:///

> file:///Users/tdurand/Library/Developer/CoreSimulator/Devices/E2D725EC-A972-4BAC-8309-2D8A13535FAA/data/Containers/Data/Application/54A5EDAB-F950-4D7D-8995-3BD5755AF52F/tmp/trim.CF765039-D257-4DB8-A9A7-3925D495942F.MOV

When i do so, just integrating like that:

```jsx
<WebView source={{ uri: "file:///Users/tdurand/Library/Developer/CoreSimulator/Devices/E2D725EC-A972-4BAC-8309-2D8A13535FAA/data/Containers/Data/Application/54A5EDAB-F950-4D7D-8995-3BD5755AF52F/tmp/trim.CF765039-D257-4DB8-A9A7-3925D495942F.MOV" }}
                  style={{height: 150 ,width: 150}}
                />
```

Is working but throw an error just after half sec, really frustrating

![xo8exe3hut](https://cloud.githubusercontent.com/assets/533590/18898049/97cce982-84f4-11e6-9f5f-b6f0b696d482.gif)

The error thrown is:

```
{
  canGoBack:false,
  canGoForward:false,
  code:204,
  description:"Plug-in handled load",
  domain:"WebKitErrorDomain",
  loading:false,
  target:155,
  title:"",
  url:"file:///Users/tdurand/Library/Developer/CoreSimulator/Devices/E2D725EC-A972-4BAC-8309-2D8A13535FAA/data/Containers/Data/Application/54A5EDAB-F950-4D7D-8995-3BD5755AF52F/tmp/trim.CF765039-D257-4DB8-A9A7-3925D495942F.MOV"
}
```

I very well looks like a bug of React Native Webview that does not authorize those urls, but before filling an issue there i would like to know if you've been able to play a video from local ?

Thanks !

**Comment by tdurand** [comment] 2016-09-29 14:23
Just to let you know that i filled an issue on React native tracker : https://github.com/facebook/react-native/issues/10171

**Comment by Vunovati** [comment] 2016-09-30 14:25
Thanks, as this is more a non ui-toolkit-specific question.

I tried to reproduce what you did with [this](http://techslides.com/demos/sample-videos/small.mp4) video and I get:

```
{
    "domain": "WebKitErrorDomain",
    "canGoBack": false,
    "target": 143,
    "code": 204,
    "loading": false,
    "title": "",
    "canGoForward": false,
    "description": "Plug-in handled load",
    "url": "file:///Users/ovca/Library/Developer/CoreSimulator/Devices/55C21DB9-9F17-4D…ainers/Data/Application/9F325E1A-7E61-4D8E-A591-26CB4DF593BE/tmp/small.mp4"
}
```

but it plays the video in the iOS video player all the way to the end. On the other hand, I cannot control it, it plays right away after it has been rendered.

This is the first time I’ve tried this since we didn’t need the playback of local files. You could maybe show some kind of poster image and then render the WebView when the image is clicked.  

I think if you want to play local videos you can also try using [react-native-video](https://github.com/react-native-community/react-native-video) as it officially supports it. Initially, we used it for our video components, but we figured out we can get away with using WebView for most of our needs.   

React Native WebView also has its limitations, especially on Android where we cannot get it to play full screen yet, but I think that can be fixed in RN in the future.

**Comment by tdurand** [comment] 2016-09-30 14:45
Hello, 

Thanks for testing. So on your device it actually plays ? On mine it replace the container with the error and that's it. (like the gif on the issue shows)

If i can get this working i may consider do the hack you suggest.

Also you may consider add a note in your Documentation telling people that it won't work for local files.

Thanks, 

PS: Yeah, i know my other alternatives, but as everyone i want to write the fewer code i can to reach my goals and avoid further maintenance ;-) . And react-native-video doesn't yet provide a nice UI with play pause, seek bar ... as native, you need to code it yourself, but i will likely need to tackle that... I'll get inspiration from the code you write, there is also :  https://github.com/ldn0x7dc/react-native-media-kit , https://github.com/charliesbox/react-native-media-controls , i must admit i'm a bit disapointed that RN doesn't provide Audio and Video component out of the box...

**Comment by Vunovati** [comment] 2016-09-30 15:12
Thanks for the tip. Media controls lib could be of use but react-native-videos has native controls prop which seems to me like a better deal. Will update docs 👍

**Comment by Vunovati** [comment] 2016-09-30 15:57
Updated docs: https://github.com/shoutem/shoutem.github.io/pull/43

**Closed by Vunovati** 2016-09-30 15:57 UTC
Labels: Hacktoberfest, info missing, question
