### ISSUE TITLE
NavigationStateUtils is deprecated since 0.43

### ISSUE THREAD

**Issue by lc3t35** [shoutem/ui#245] opened 2017-05-06 18:46 UTC
NavigationStateUtils is used in RestaurantsApp/app/redux.js, as of React Native 0.43, NavigationExperimental is deprecated (https://facebook.github.io/react-native/docs/navigation.html). It will be removed from the codebase in a later version.

Can you provide a new implementation of redux.js ?

**Comment by Vladimir-Vdovic** [comment] 2017-06-05 18:04
The current workaround (until we update the UI toolkit) is to set up dependencies for your project (and reinstall node modules) as described by user dobrienlzd: 

https://github.com/shoutem/ui/issues/241#issuecomment-298602614.

Marking this issue as a duplicate of https://github.com/shoutem/ui/issues/241 and closing it.

Please reference mentioned issue for future updates.

**Closed by Vladimir-Vdovic** 2017-06-05 18:04 UTC
Labels: duplicate

**Comment by license2e** [comment] 2017-09-28 17:21
for those who want to run the example in the directory (until they fix the example), you can download the NavigationStateUtils.j from here: https://github.com/facebook/react-native/blob/9ee815f6b52e0c2417c04e5a05e1e31df26daed2/Libraries/NavigationExperimental/NavigationStateUtils.js
