### ISSUE TITLE
TextInput reference doesn't have focus() method.

### ISSUE THREAD

**Issue by mypark** [shoutem/ui#130] opened 2017-01-14 13:56 UTC
I'm trying to implement next focus in a form 

http://stackoverflow.com/questions/32748718/react-native-how-to-select-the-next-textinput-after-pressing-the-next-keyboar

However, the focus() method doesn't exist in shoutem/ui's implementaiton of text input.  I tried `this.refs.SecondInput.wrappedInstance.wrappedInstance` of textinput but that didn't have a focus method either.

<TextInput 
  style = {styles.titleInput}
  returnKeyType = {"next"}
  autoFocus = {true}
  placeholder = "Title"
  onSubmitEditing={(event) => { 
    this.refs.SecondInput.focus(); 
  }}
/>
<TextInput
  ref='SecondInput'
  style = {styles.descriptionInput}          
  multiline = {true}
  maxLength = {200}
  placeholder = "Description" />

**Comment by mypark** [comment] 2017-01-15 01:48
Maybe something like a getRenderedComponent() method would help?

this.refs.firstField 
    .getRenderedComponent() 
    .focus() 

e.g. https://github.com/erikras/redux-form-material-ui/blob/master/src/createComponent.js

**Comment by SoHotSoup** [comment] 2017-01-18 09:00
Hey guys, thank you for submitting issue, this is general issue with our components, and its caused by our higher order components. This actual one is duplicate of https://github.com/shoutem/ui/issues/44, but we are working on solution to cover all methods in general. Thank you.

**Closed by SoHotSoup** 2017-01-18 09:00 UTC
