### ISSUE TITLE
UNMET PEER DEPENDENCIES

### ISSUE THREAD

**Issue by mnehal69** [shoutem/ui#273] opened 2017-06-25 16:53 UTC
Hi,
These are the versions for my react native application
 "@shoutem/ui": "^0.15.0",
    "react": "16.0.0-alpha.12",
    "react-native": "0.45.1"
While installing shoutem-ui@0.15.0, i ran into a issue:
```
npm WARN @shoutem/ui@0.15.0 requires a peer of react@^15.0.0 but none was installed.
npm WARN @shoutem/animation@0.11.0 requires a peer of react@^15.0.0 but none was installed.
npm WARN @shoutem/theme@0.9.0 requires a peer of react@^15.1.0 but none was installed.
```
And if i try to render an app, i get an error:

> WHAT IT SHOULD LOOK LIKE
http://imgur.com/a/23czQ

> RED ERROR MESSAGE
http://imgur.com/a/BUXF6

**Comment by rey1024** [comment] 2017-06-27 01:35
Same issue : 
`D:\rnative\Belajar\AppBelajar1>npm install --save @shoutem/ui
AppBelajar1@0.1.0 D:\rnative\Belajar\AppBelajar1
+-- @shoutem/ui@0.16.0
| +-- @shoutem/animation@0.11.0
| +-- @shoutem/theme@0.9.0
| +-- buffer@4.5.1
| | `-- ieee754@1.1.8
| +-- events@1.1.0
| +-- html-entities@1.2.1
| +-- htmlparser2@3.9.2
| | +-- domelementtype@1.3.0
| | +-- domhandler@2.4.1
| | +-- domutils@1.6.2
| | | `-- dom-serializer@0.1.0
| | |   `-- domelementtype@1.1.3
| | `-- entities@1.1.1
| +-- lodash@4.15.0
| +-- qs@4.0.0
| +-- UNMET PEER DEPENDENCY react@^15.0.0
| +-- react-native-lightbox@0.7.0  (git://github.com/shoutem/react-native-lightbox.git#4e58b9b1aca166142d69b161ff511efc3358ff9f)
| | `-- react-native-view-transformer@0.0.28  (git://github.com/ldn0x7dc/react-native-view-transformer.git#f7e028b6566022deac4e523052e74c2c63a4af7e)
| |   +-- react-native-gesture-responder@0.1.1
| |   `-- react-native-scroller@0.0.6
| +-- react-native-linear-gradient@2.0.0
| +-- react-native-photo-view@1.2.0
| +-- react-native-share@1.0.20
| +-- react-native-transformable-image@0.0.19  (git://github.com/shoutem/react-native-transformable-image.git#7d15395ec3857571711a12bc08f24f3a96ff1cde)
| +-- react-native-vector-icons@4.0.1
| +-- stream@0.0.2
| | `-- emitter-component@1.1.1
| `-- tinycolor2@1.3.0
+-- expo@18.0.4
| +-- UNMET PEER DEPENDENCY react@>=15.4.0
| +-- react-native-fbads@4.1.0
| +-- react-native-maps@0.15.2
| +-- react-native-svg@5.2.0
| `-- websql@0.4.4  (git://github.com/expo/node-websql.git#e364fa65146a9e2157a19e5c719e7702c2b6b87a)
`-- UNMET PEER DEPENDENCY react@16.0.0-alpha.12`

my package.json
`{
  "name": "AppBelajar1",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "react-native-scripts": "0.0.40",
    "jest-expo": "~18.0.0",
    "react-test-renderer": "16.0.0-alpha.12"
  },
  "main": "./node_modules/react-native-scripts/build/bin/crna-entry.js",
  "scripts": {
    "start": "react-native-scripts start",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios",
    "test": "node node_modules/jest/bin/jest.js --watch"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@shoutem/ui": "^0.16.0",
    "expo": "^18.0.3",
    "react": "16.0.0-alpha.12",
    "react-native": "^0.45.1"
  }
}
`

**Comment by Vladimir-Vdovic** [comment] 2017-06-27 08:44
The current workaround (until we update the UI toolkit) is to set up dependencies for your project (and reinstall node modules) as described by user dobrienlzd: 

https://github.com/shoutem/ui/issues/241#issuecomment-298602614.

Going to mark this issue as a duplicate of https://github.com/shoutem/ui/issues/241.

Please reference mentioned issue for future updates.

**Closed by Vladimir-Vdovic** 2017-06-27 08:44 UTC
