### ISSUE TITLE
React Native 0.44 Incompatible

### ISSUE THREAD

**Issue by darkredz** [shoutem/ui#244] opened 2017-05-03 14:44 UTC
RN 0.44 introduced a breaking change that makes this library incompatible with it. CustomComponents had been removed from RN

Remove CustomComponents folder and license (777e80a) - https://github.com/facebook/react-native/releases

**Comment by aswinmohanme** [comment] 2017-05-04 00:37
In the meantime should we downgrade to RN 43 ?

**Comment by Vladimir-Vdovic** [comment] 2017-06-05 18:03
The current workaround (until we update the UI toolkit) is to set up dependencies for your project (and reinstall node modules) as described by user dobrienlzd: 

https://github.com/shoutem/ui/issues/241#issuecomment-298602614.

Marking this issue as a duplicate of https://github.com/shoutem/ui/issues/241 and closing it.

Please reference mentioned issue for future updates.

**Closed by Vladimir-Vdovic** 2017-06-05 18:03 UTC
Labels: duplicate
