### ISSUE TITLE
Shoutem UI should be maintained!!!

### ISSUE THREAD

**Issue by kreshnikalidema** [shoutem/ui#260] opened 2017-05-27 20:04 UTC
Today I have tried for the first time Shoutem UI, and I think there are many useful components but I think it is not maintained as it should.
In console with browser debug I saw 5 erros which are:
NavigationExperimental is deprecated
React.PropTypes is deprecated
...
Do you intend to maintain it?

**Comment by Vladimir-Vdovic** [comment] 2017-05-29 11:34
We're actively working on it.

For the time being you can utilise this workaround:
https://github.com/shoutem/ui/issues/241#issuecomment-298602614

**Comment by Vladimir-Vdovic** [comment] 2017-06-05 18:05
Marking this issue as a duplicate of https://github.com/shoutem/ui/issues/241 and closing it.

Please reference mentioned issue for future updates.

**Closed by Vladimir-Vdovic** 2017-06-05 18:05 UTC
Labels: duplicate, question

**Comment by mnlbox** [comment] 2017-06-20 13:40
+1 for more bug fix and maintain more. I also give a try shoutem yesterday but it has many error and I can't run Example. It's a little bad memories for first appointment.

**Comment by tquiroga** [comment] 2017-10-11 17:07
Thank you for fixing NavigationExperimental in #241 
Now, RN 0.49 is using React 16 which means `React.PropTypes` doesn't exists anymore, so the repo is not working at all on any recent project... We need a merge of #314 please.

**Comment by JulianKingman** [comment] 2017-10-30 10:02
Having tried other UI libraries, shoutem is hands down the best. At every turn I find things are done smartly and efficiently. I agree that it would be great to see more active support so this can become the “go-to” UI library like bootstrap is for web.
