### ISSUE TITLE
Can't run the basic @shoutem/ui example

### ISSUE THREAD

**Issue by davidsamacoits** [shoutem/ui#267] opened 2017-06-09 21:14 UTC
I'm trying to run the basic @shoutem/ui example but it's not working. Copied and pasted the code from this page http://shoutem.github.io/docs/ui-toolkit/introduction and I get a wonderful _"Cannot read property 'Header' of undefined"_

![capture](https://user-images.githubusercontent.com/27018364/26994689-e2fb98a8-4d68-11e7-87f8-3dfe6910442c.png)

This is the code I used : 

```
import React, { Component } from 'react';
import { AppRegistry } from 'react-native';
import { Examples } from '@shoutem/ui';

class Girafe extends Component {
  render() {
    return (
      <Examples />
    );
  }
}

AppRegistry.registerComponent('Girafe', () => Girafe);
```

My environnement setup : 
- MacOS Sierra: 10.12.5
- XCode: 8.3.2
- react-native-cli: 2.0.1
- react-native: 0.44.2

**Comment by Vladimir-Vdovic** [comment] 2017-06-09 21:21
The current workaround (until we update the UI toolkit) is to set up dependencies for your project (and reinstall node modules) as described by user dobrienlzd: 

https://github.com/shoutem/ui/issues/241#issuecomment-298602614.

Going to mark this issue as a duplicate of https://github.com/shoutem/ui/issues/241.

Please reference mentioned issue for future updates.

**Closed by Vladimir-Vdovic** 2017-06-09 21:21 UTC
