### ISSUE TITLE
undefined is not an object (evaluating '_reactNative.NavigationExperimental.Header')

### ISSUE THREAD

**Issue by mnlbox** [shoutem/ui#272] opened 2017-06-19 11:56 UTC
I try to install shoutem.ui with below commands:
```
react-native install @shoutem/ui
react-native link
```
And put this code in `index.android.js`:
```
import React, { Component } from 'react';
import { AppRegistry } from 'react-native';
import { Examples } from '@shoutem/ui';

class HelloWorld extends Component {
    render() {
        return (
            <Examples />
        );
    }
}

AppRegistry.registerComponent('TestApp', () => HelloWorld);
```

But it's return below error:
![screenshot_2017-06-19-16-21-09](https://user-images.githubusercontent.com/25859075/27283951-e6cbe8ac-550b-11e7-9dc8-2a543b5bfb54.png)

Have you any suggestion for fix it?

**Comment by Vladimir-Vdovic** [comment] 2017-06-19 16:10
The current workaround (until we update the UI toolkit) is to set up dependencies for your project (and reinstall node modules) as described by user dobrienlzd: 

https://github.com/shoutem/ui/issues/241#issuecomment-298602614.

Going to mark this issue as a duplicate of https://github.com/shoutem/ui/issues/241.

Please reference mentioned issue for future updates.

**Closed by Vladimir-Vdovic** 2017-06-19 16:10 UTC
