### ISSUE TITLE
Error when running the application on ios simolator

### ISSUE THREAD

**Issue by rachip** [shoutem/ui#24] opened 2016-09-16 05:18 UTC
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Error in config: 

[Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier  #/Users/***/Desktop/ui/examples/RestaurantsApp/ios/build/Build/Products/Debug-iphonesimulator/ShoutemRestaurants.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

**Comment by tenodi** [comment] 2016-09-16 09:15
Have you tried running `react-native upgrade`?

**Comment by vpanjganj** [comment] 2016-09-19 14:55
@tenodi I upgraded but the issue persists.

**Comment by kenmjlee** [comment] 2016-09-20 16:19
Update React Native to 0.33.0 then it will pass compilation. However, I still have several problems during I try to run the example and add shoutem/ui to my project - even if it's a new project. 

1. for the example, I got this error - TransformError: /Users/prj/shoutem/examples/RestaurantsApp/index.ios.js: Couldn't find preset "react-native" relative to directory "/Users/prj/shoutem"",

2. Not easy to connect to localhost:8081. Have to refresh many times.

3. Once it connected to localhost, it tells me "Unable to resolve module string_decoder from /Users/prj/mobile-apps/node_modules/@shoutem/ui/node_modules/htmlparser2/lib/WritableStream.js: Unable to find this module in its module map or any of the node_modules directories" 

I'm still figuring out what happens, but it looks no luck for me.

**Comment by SoHotSoup** [comment] 2016-09-20 17:37
Could you tell us what version of xcode do you use? Also it looks like npm didn't resolve all the dependencies right.

**Comment by kenmjlee** [comment] 2016-09-20 23:23
xcode 8，the latest one.

**Comment by kenmjlee** [comment] 2016-09-20 23:25
I'll try to use an old version to try again.

**Comment by brunolemos** [comment] 2016-09-23 19:29
I'm also can't run it.
```
Unable to resolve module react-native-lightbox from ...
Unable to find this module in its module map or any of the node_modules...
```

[![Screenshot of error](http://s11.postimg.org/h45oc2e6b/Screen_Shot_2016_09_23_at_16_25_05.png)](http://postimg.org/image/4003zdm4f/)

macOS Sierra 10.12
Simulator: iOS 10 
Xcode 8
@shoutem/ui ^0.8.5

**Comment by zvoncha** [comment] 2016-10-05 12:19
I had the same problem with building for Android as well for iOS. The solution was deleting `.babelrc` file from /node-modules/@shoutem/ui

**Comment by felixaa** [comment] 2016-10-13 21:05
Transform error with same errormessage as @kenmjlee aswell... Hmm.

**Comment by kenmjlee** [comment] 2016-10-19 08:45
@zvoncha  It seems `.bablerc` has been removed in 0.9.1, though, it still doesn't work.

**Comment by aliemre** [comment] 2016-11-13 00:26
React Native Cli 1.2.0 and React Native 0.37 still does not working.

**Comment by patrickdevivo** [comment] 2016-11-27 22:31
+1 having same issue with CLI 1.2.0 and RN 0.38.0

**Comment by SoHotSoup** [comment] 2016-12-07 15:26
I could not reproduce this with new version of `@shoutem/ui`. Could someone of you guys verify this issue doesn't exist anymore?

**Comment by thejpanganiban** [comment] 2017-02-05 18:01
Issue still persists. CLI 2.0.1 and React Native 0.41.1

**Comment by mouthzipper** [comment] 2017-02-06 17:31
Same issue. CLI 2.0.1 and React Native 0.41.1

**Comment by mpjraaij** [comment] 2017-02-16 19:00
Same issue here as well. Would love to hear how to solve this.

<img width="377" alt="screen shot 2017-02-16 at 19 59 15" src="https://cloud.githubusercontent.com/assets/9059975/23036257/6d6314e8-f482-11e6-938a-932a17e198ad.png">

**Comment by 3DEsprit** [comment] 2017-03-18 19:49
I just had this happen last night after I upgraded to 0.40.0 (and persisted after 0.41.0) where I had to remove and reinstall shoutem/ui due to the pre 0.40.0 dependencies not working. 

Could this be an issue that comes with 0.11.0 that is installed when RN is 0.40.0+?

**Comment by zrumenjak** [comment] 2017-04-06 14:31
This issue contains many unrelated issues. I am closing it now, please open new issues if anything from the comments above is still relevant.

**Closed by zrumenjak** 2017-04-06 14:31 UTC
