### ISSUE TITLE
Could not add StyleSheet to <TextInput>

### ISSUE THREAD

**Issue by JoshYuJump** [shoutem/ui#321] opened 2017-10-16 10:42 UTC
When I add StyleSheet to <TextInput>, it failed.
```
<TextInput
    placeholder={'Password'}
    style={styles.inputText}
/>
```
`inputText` is defined in the following code.
```
const styles = StyleSheet.create({
  inputText: {
    flex: 1, 
    height: 30, 
    lineHeight: 30, 
    paddingVertical: 0
  },
})
```

It success if I write like that:
```
<TextInput
    placeholder={'Mobile'}
    style={{flexGrow: 1, height: 30, lineHeight: 30, paddingVertical: 0}}
/>
```

**Comment by thallysrc** [comment] 2017-10-16 15:58
I reproduced this bug , and the `const styles = StyleSheet.create()` creates a styles.inputText with a number type instead of object

if you insert this console 
` console.log(typeof styles.inputText)` 
after this
```
const styles = StyleSheet.create({
  inputText: {
    flex: 1, 
    height: 30, 
    lineHeight: 30, 
    paddingVertical: 0
  },
})
```
you'll see the type of styles.inputText are `Number` and the component TextInput expect `object` you can remove the StyleSheet.create()
```
    const styles = {
      inputText: {
        flex: 1, 
        height: 30, 
        lineHeight: 30, 
        paddingVertical: 0,
        backgroundColor: 'red'
      },
    }
```
it works for me, but i'll make a pull request to fix this. peace!

**Comment by Vladimir-Vdovic** [comment] 2017-12-18 06:35
Closing issue, you can find the solution/workaround [here](https://github.com/shoutem/ui/pull/322#issuecomment-352032215).

**Closed by Vladimir-Vdovic** 2017-12-18 06:35 UTC
