### ISSUE TITLE
Cannot build android with latest version of RN

### ISSUE THREAD

**Issue by brandon-dewitt** [shoutem/ui#313] opened 2017-09-12 23:05 UTC
RN: 0.48.3
@shoutem/ui: 0.21.3

Looks like react-native-linear-gradient is the issue and fixed in 2.2.0: https://github.com/react-native-community/react-native-linear-gradient/issues/202

**Comment by Vladimir-Vdovic** [comment] 2017-09-13 06:18
Duplicate of [this issue](https://github.com/shoutem/ui/issues/306).

Temporary workaround can be found there. We will update our dependencies in an upcoming release of the UI toolkit.

**Closed by Vladimir-Vdovic** 2017-09-13 06:18 UTC
